### ISSUE TITLE
[CI/CD] Push message to slack on build fail

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-client#170]
**Is your feature request related to a problem? Please describe.**
Push message to slack on build fail

**Comment by gaupoit** [comment]
hi @djhahe , please have a look this PR https://github.com/CasperDash/casperdash-client/pull/145. It will run the UT and build scripts on every PR into `develop` and `master` branch. Currently, the PR is failed to build due to this https://github.com/CasperDash/casperdash-client/issues/143. Feel free to merge it first. Cheers. 

![Screen Shot 2022-10-17 at 11 42 42](https://user-images.githubusercontent.com/4486806/196091014-2c6e6ba3-95be-48bf-b7f4-ec432abda8bc.png)
